### ISSUE TITLE
[New Help system]:  NameError: name 's' is not defined

### ISSUE THREAD

**Issue by ebrahimraeyat** [yorikvanhavre/FreeCAD-Help#1]
thanks for this great system help.

I cloned the repository, restarted FreeCAD, then typed this commands, gives me this error:

```
>>> import Help
>>> Help.show("Draft Line")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\ebi\AppData\Roaming\FreeCAD\Mod\FreeCAD-Help\Help.py", line 86, in show
    html = convert(md)
  File "C:\Users\ebi\AppData\Roaming\FreeCAD\Mod\FreeCAD-Help\Help.py", line 225, in convert
    html = convert_raw(content)
  File "C:\Users\ebi\AppData\Roaming\FreeCAD\Mod\FreeCAD-Help\Help.py", line 201, in convert_raw
    m = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>",s) # bold
NameError: name 's' is not defined
>>> 
```

Thanks

**Comment by yorikvanhavre** [comment]
Fixed by #2
